apiVersion: batch/v1
kind: Job
metadata:
  name: job-prod-wq-2
spec:
  parallelism: 1
  template:
    metadata:
      name: job-prod-wq-2
    spec:
      containers:
      - name: c
        image: benjbaron/job-prod-wq-2:latest
      restartPolicy: OnFailure
