apiVersion: batch/v1
kind: Job
metadata:
  name: job-cons-wq-2
spec:
  parallelism: 2
  template:
    metadata:
      name: job-cons-wq-2
    spec:
      containers:
      - name: c
        image: benjbaron/job-cons-wq-2:latest
      restartPolicy: OnFailure
